### ISSUE TITLE
result is not good

### ISSUE THREAD

**Issue by flynnamy** [menyifang/DCT-Net#16]
Hi, I use anime style model to test celeb dataset. It has some bad cases and artifacts. The pose seems not large. How to solve this? Thanks! @menyifang 
![image](https://user-images.githubusercontent.com/20398890/184791799-252988ee-de8e-454e-9e52-2955f3c4940b.png)
![image](https://user-images.githubusercontent.com/20398890/184791945-f3632e83-ecf3-45f7-b907-fb9089969f97.png)

**Comment by menyifang** [comment]
We can not promise all results are perfect, but most are good for celeba as following. You can show the origin source image and i will give a try.
![image](https://user-images.githubusercontent.com/47292223/186403286-2de9db09-5d9f-4554-84cf-e3c53a91980b.png)
