### ISSUE TITLE
how to train keypoints model

### ISSUE THREAD

**Issue by kitterive** [menyifang/DCT-Net#31]
I convert keypoints from tf pb model to onnx, and found the result is not same pb model result.

**Comment by kitterive** [comment]
可能是由于keypoints和 detect 两个模型都有traning flag的原因，在导出模型时，能去掉training flag这个输入吗，设为固定值False, 这样就一个输入，比较适合推理

**Comment by kitterive** [comment]
solved

**Comment by cv-nlp** [comment]
请问下您是怎么解决的呢？tf2onnx的时候能设置固定输入吗？有没有转换脚本呢
