### ISSUE TITLE
关于使用stylegan2训练内容校准网络的作用疑惑

### ISSUE THREAD

**Issue by huaze555** [menyifang/DCT-Net#57]
大牛您好，我看训练步骤里，第一步是用stylegan2训练风格化图片，
请问训练完这个stylegan的作用是什么呢？只是为了后续用这个stylegan生成更多的风格化图片，然后进行第三步训练纹理迁移网络吗？ 或者说，第一步的内容校准网络和第三步的纹理迁移网络，是啥关联呢？我看代码里，第三步训练纹理迁移网络时，并没有用到第一步训练好的stylegan2模型。
求大佬解惑

**Comment by QianhuiWu** [comment]
> 大牛您好，我看训练步骤里，第一步是用stylegan2训练风格化图片， 请问训练完这个stylegan的作用是什么呢？只是为了后续用这个stylegan生成更多的风格化图片，然后进行第三步训练纹理迁移网络吗？ 或者说，第一步的内容校准网络和第三步的纹理迁移网络，是啥关联呢？我看代码里，第三步训练纹理迁移网络时，并没有用到第一步训练好的stylegan2模型。 求大佬解惑

这个问题解决了嘛？ Train content calibration net 有什么特别的作用嘛？

**Comment by h3clikejava** [comment]
这个问题解决了嘛？ Train content calibration net 有什么特别的作用嘛？如果不用stylegan生成数据可以不用吗？
